### PR TITLE
Adding example models

### PR DESCRIPTION
**Pull request by ryankscott**
Adding some example models to get the ball rolling. I'm making some assumptions like we're going to use UUIDs for IDs. 

I've also added a concept of a Status which would allow us to have multiple transitions. We could collapse this to an enum for a first cut.

Also, what's the difference between an Event and a Task?

### CODE REVIEW

**Comment by d4ncer** [comment]
Good assumption on UUIDs. Status sounds good.

My initial thoughts on Event vs. Task:
- A Task has work required from the user in order to move it between states, all of which is user defined. An Event is something that is scheduled in the material world that the user is participating in, and has only a SCHEDULED & DONE state. Any work done in preparation for an Event or actions that come out of the Event should be Tasks.

This is all purely arbitrary and up for debate. What do you think?

**Comment by ryankscott** [comment]
Got it, so it would be analogous to a calendar event? Makes sense. 

What's your thoughts on multiple statuses? Should we just constrain to "TODO" "NEXT" "IN PROGRESS" "DONE" "WON'T DO" ?

**Comment by d4ncer** [comment]
Exactly. 

Unsure. We can be prescriptive or go down the JIRA approach of being able to create complex state machines. Maybe start with what you suggested and then expand later? We should add a status for tasks that are waiting on external action (WAITING or something similar).

**Comment by d4ncer** [comment]
Do we want Statuses to be associated with just Tasks or Events, Projects, and Notes too? If so, probably need different sets of Statuses for each entity.

**Comment by ryankscott** [comment]
Perhaps if we just start with statuses on Tasks that'll work. Projects might be the next logical one but it would be simpler like: "TODO | IN PROGRESS | DONE"

**Comment by d4ncer** [comment]
Sounds good to me.

**Comment by d4ncer** [comment]
this can be merged @ryankscott

**Pull request closed without merging**
